spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  springfox:
    documentation:
     swagger-ui:
        enabled: true